export default class DarciNFO {
        constructor() {
                this.darc = {
                        name : 'darc',
                        meaning : {
                            D : 'daniel',
                            A : 'Asani',
                            R : 'revolutuonary',
                            C : 'computers'
                        },
                       format : {
                            file: 'tsb',
                            games: 'nbl'
                       } 
                }
        }
}
export const darcInfo = new DarciNFO